"""
Generate 10 new synthetic bills (v2-016 through v2-025) for Sadaf.
Writes both evaluator (synthetic_bills_v2/) and agent (synthetic_bills_v2_agent/) versions.
"""

import json, os

OUT_EVAL  = "synthetic_bills_v2"
OUT_AGENT = "synthetic_bills_v2_agent"

FACILITY = {
    "name": "Cedars-Sinai Medical Center",
    "address": "8700 Beverly Blvd, Los Angeles, CA 90048",
    "npi": "1316230813",
    "tax_id": "95-2123461"
}

PATIENT_SERVICES = {
    "department": "Patient Financial Services",
    "phone": "866-803-1777",
    "hours": "Monday–Friday, 8:00 AM – 4:30 PM PT",
    "online": "https://www.cedars-sinai.org/patients-visitors/billing.html",
    "mail": "Cedars-Sinai Medical Center, P.O. Box 48750, Los Angeles, CA 90048"
}

STRIP_KEYS = {"_schema_version", "_note", "_intentional_error_note"}

NOTE = "This is a synthetic patient billing statement for evaluation purposes. No real PHI. Generated by LMU MSBA × Cedars-Sinai capstone team."

def make_totals(items):
    tb  = round(sum(i["billed_amount"]        for i in items), 2)
    tip = round(sum(i["insurance_payments"]   for i in items), 2)
    ta  = round(sum(i["adjustments"]          for i in items), 2)
    os_ = round(tb - tip - ta, 2)
    pb  = round(sum(i["patient_balance"]      for i in items), 2)
    assert abs(os_ - pb) < 0.01, f"outstanding {os_} != patient_balance {pb}"
    return {
        "total_billed": tb,
        "total_insurance_payments": tip,
        "total_adjustments": ta,
        "outstanding_balance": os_,
        "patient_balance": pb
    }

def li(service_name, code_type, code, qty, unit, billed, ins=0.0, adj=0.0):
    patient = round(billed - ins - adj, 2)
    return {
        "service_name": service_name,
        "code_type": code_type,
        "code": code,
        "quantity": qty,
        "unit": unit,
        "billed_amount": billed,
        "insurance_payments": ins,
        "adjustments": adj,
        "patient_balance": patient
    }

BILLS = []

# ─── BILL 16: Complex Cardiac Inpatient (30+ lines) ──────────────────────────
# HH=2, income $73,000 → 314% FPL → Charity Care
items16 = [
    li("Emergency Department – Level 5",       "CPT",     "99285",  1, "each",  4200.0,  3696.0,    0.0),
    li("Inpatient Room & Board – Semi-Private", "Revenue", "0110",  5, "day",  28000.0, 24640.0,    0.0),
    li("Coronary Care Unit – Intensive",        "Revenue", "0210",  2, "day",  14000.0, 12320.0,    0.0),
    li("Cardiac Catheterization – Diagnostic",  "CPT",     "93454",  1, "each",  8500.0,  7480.0,    0.0),
    li("Percutaneous Coronary Intervention",    "CPT",     "92928",  1, "each",  9800.0,  8624.0,    0.0),
    li("Drug-Eluting Stent (×2)",               "HCPCS",   "C1877",  2, "each",  4800.0,  4224.0,    0.0),
    li("Cardiac Monitoring – Telemetry",        "Revenue", "0730",   5, "day",   3500.0,  3080.0,    0.0),
    li("12-Lead ECG",                           "CPT",     "93005",  3, "each",   600.0,   528.0,    0.0),
    li("Echocardiogram – Transthoracic",        "CPT",     "93306",  1, "each",  4600.0,  4048.0,    0.0),
    li("Troponin (×4)",                         "CPT",     "84484",  4, "each",   960.0,   845.0,    0.0),
    li("BNP",                                   "CPT",     "83880",  2, "each",   480.0,   422.0,    0.0),
    li("Complete Metabolic Panel (×3)",         "CPT",     "80053",  3, "each",   720.0,   634.0,    0.0),
    li("CBC with Differential (×3)",            "CPT",     "85025",  3, "each",   450.0,   396.0,    0.0),
    li("Coagulation Panel (×2)",                "CPT",     "85730",  2, "each",   300.0,   264.0,    0.0),
    li("Chest X-Ray (×2)",                      "CPT",     "71046",  2, "each",   480.0,   422.0,    0.0),
    li("CT Angiography – Coronary",             "CPT",     "75574",  1, "each",  5200.0,  4576.0,    0.0),
    li("Pharmacy – Aspirin/Clopidogrel/Heparin","Revenue", "0250",   1, "each",  1200.0,  1056.0,    0.0),
    li("Pharmacy – Metoprolol",                 "Revenue", "0250",   1, "each",   480.0,   422.0,    0.0),
    li("Pharmacy – Atorvastatin",               "Revenue", "0250",   1, "each",   360.0,   317.0,    0.0),
    li("Pharmacy – Nitroglycerin IV",           "Revenue", "0250",   1, "each",   840.0,   739.0,    0.0),
    li("IV Administration – Initial Hour",      "CPT",     "96365",  1, "each",   480.0,   422.0,    0.0),
    li("IV Administration – Each Add'l Hour (×8)","CPT",   "96366",  8, "each",  1600.0,  1408.0,    0.0),
    li("Oxygen – Supplemental",                 "Revenue", "0410",   5, "day",    750.0,   660.0,    0.0),
    li("Physical Therapy – Cardiac Rehab Eval", "CPT",     "97001",  1, "each",   600.0,   528.0,    0.0),
    li("Dietitian Consultation",                "CPT",     "97802",  1, "each",   320.0,   282.0,    0.0),
    li("Social Work Consultation",              "Revenue", "0560",   1, "each",   280.0,   246.0,    0.0),
    li("Medical/Surgical Supplies",             "Revenue", "0270",   1, "each",  1800.0,  1584.0,    0.0),
    li("OR Facility Fee – PCI Suite",           "Revenue", "0360",   1, "each",  4200.0,  3696.0,    0.0),
    li("Anesthesia – Moderate Sedation",        "CPT",     "99152",  1, "each",   900.0,   792.0,    0.0),
    li("Pulmonary Function Test",               "CPT",     "94010",  1, "each",   560.0,   493.0,    0.0),
]
totals16 = make_totals(items16)
BILLS.append({
    "_schema_version": "2.0",
    "_note": NOTE,
    "facility": FACILITY,
    "statement_date": "2026-06-01",
    "due_date": "2026-07-01",
    "patient": {
        "patient_name": "Robert Chambers",
        "patient_account_number": "CS-2026-07811",
        "service_date": "2026-05-10"
    },
    "guarantor": {
        "guarantor_name": "Robert Chambers",
        "guarantor_account_number": "GU-2026-07811"
    },
    "insurance": {
        "primary": "Blue Shield of California – PPO (Commercial)",
        "secondary": "None on file"
    },
    "summary_of_services": {
        "line_items": items16,
        "totals": totals16
    },
    "payment_detail": {
        "insurance_payments": [
            {"payer_name": "Blue Shield of California PPO", "payment_amount": totals16["total_insurance_payments"], "payment_date": "2026-05-28", "check_or_ref_number": "BSC-2026-07811-01"}
        ],
        "adjustments": []
    },
    "total_amount_due": totals16["outstanding_balance"],
    "patient_services": PATIENT_SERVICES,
    "_eval_metadata": {
        "case_id": "DV2-016",
        "household_size": 2,
        "annual_income_usd": 73000,
        "fpl_percentage": 314.0,
        "expected_eligibility_tier": "Charity Care (314% FPL, HH=2)",
        "scenario_tags": ["complex_cardiac", "inpatient", "commercial_ppo", "30_line_items"]
    }
})

# ─── BILL 17: Maternity Inpatient ────────────────────────────────────────────
# HH=3, income $72,000 → 285% FPL → Charity Care
items17 = [
    li("Labor & Delivery – Vaginal Delivery",   "CPT",     "59400",  1, "each", 12000.0, 9480.0,  1200.0),
    li("Inpatient Room & Board – Semi-Private", "Revenue", "0110",   3, "day",  15000.0,11850.0,  1500.0),
    li("Nursery – Newborn, Well Baby",          "Revenue", "0170",   3, "day",   4500.0, 3555.0,   450.0),
    li("Epidural Anesthesia",                   "CPT",     "01967",  1, "each",  5500.0, 4345.0,   550.0),
    li("Fetal Monitoring – External",           "Revenue", "0730",   1, "each",   800.0,  632.0,    80.0),
    li("Ultrasound – Obstetric (×2)",           "CPT",     "76805",  2, "each",  1200.0,  948.0,   120.0),
    li("GBS Culture",                           "CPT",     "87081",  1, "each",   180.0,  142.0,    18.0),
    li("CBC – Postpartum",                      "CPT",     "85025",  2, "each",   300.0,  237.0,    30.0),
    li("Type & Screen",                         "CPT",     "86900",  1, "each",   240.0,  190.0,    24.0),
    li("IV Administration – Oxytocin Drip",     "CPT",     "96365",  1, "each",   480.0,  379.0,    48.0),
    li("Pharmacy – Oxytocin 10u/mL",            "Revenue", "0250",   1, "each",   320.0,  253.0,    32.0),
    li("Pharmacy – Group B Strep Antibiotics",  "Revenue", "0250",   1, "each",   480.0,  379.0,    48.0),
    li("Pharmacy – Postpartum Pain Management", "Revenue", "0250",   1, "each",   600.0,  474.0,    60.0),
    li("Medical/Surgical Supplies",             "Revenue", "0270",   1, "each",  1200.0,  948.0,   120.0),
    li("Lactation Consultation",                "CPT",     "99401",  1, "each",   280.0,  221.0,    28.0),
    li("Social Work – Discharge Planning",      "Revenue", "0560",   1, "each",   280.0,  221.0,    28.0),
    li("Newborn Hearing Screen",                "CPT",     "92585",  1, "each",   180.0,  142.0,    18.0),
    li("Newborn Metabolic Screen",              "Revenue", "0300",   1, "each",   160.0,  126.0,    16.0),
    li("Circumcision (elective)",               "CPT",     "54150",  1, "each",   480.0,  379.0,    48.0),
    li("Rhogam (if applicable)",                "HCPCS",   "J2790",  1, "each",   320.0,  253.0,    32.0),
]
totals17 = make_totals(items17)
BILLS.append({
    "_schema_version": "2.0",
    "_note": NOTE,
    "facility": FACILITY,
    "statement_date": "2026-06-10",
    "due_date": "2026-07-10",
    "patient": {
        "patient_name": "Jessica Park",
        "patient_account_number": "CS-2026-08102",
        "service_date": "2026-05-18"
    },
    "guarantor": {
        "guarantor_name": "David Park",
        "guarantor_account_number": "GU-2026-08102"
    },
    "insurance": {
        "primary": "Anthem Blue Cross – HMO (Commercial)",
        "secondary": "None on file"
    },
    "summary_of_services": {
        "line_items": items17,
        "totals": totals17
    },
    "payment_detail": {
        "insurance_payments": [
            {"payer_name": "Anthem Blue Cross HMO", "payment_amount": totals17["total_insurance_payments"], "payment_date": "2026-06-04", "check_or_ref_number": "ABC-2026-08102-01"}
        ],
        "adjustments": [
            {"description": "Anthem Blue Cross Contractual Adjustment", "amount": totals17["total_adjustments"]}
        ]
    },
    "total_amount_due": totals17["outstanding_balance"],
    "patient_services": PATIENT_SERVICES,
    "_eval_metadata": {
        "case_id": "DV2-017",
        "household_size": 3,
        "annual_income_usd": 72000,
        "fpl_percentage": 285.0,
        "expected_eligibility_tier": "Charity Care (285% FPL, HH=3)",
        "scenario_tags": ["maternity", "inpatient", "commercial_hmo", "newborn"]
    }
})

# ─── BILL 18: Secondary Insurance COB ────────────────────────────────────────
# HH=4, income $105,000 → 318% FPL → Charity Care
items18 = [
    li("Inpatient Room & Board – Semi-Private", "Revenue", "0110",   7, "day",  35000.0, 28000.0, 3500.0),
    li("Intensive Care Unit – Level 1",         "Revenue", "0200",   2, "day",  14000.0, 11200.0, 1400.0),
    li("OR Facility Fee – General",             "Revenue", "0360",   1, "each", 12000.0,  9600.0, 1200.0),
    li("Laparoscopic Colon Resection",          "CPT",     "44204",  1, "each", 18000.0, 14400.0, 1800.0),
    li("Pathology – Surgical Specimen",         "CPT",     "88305",  1, "each",  1200.0,   960.0,  120.0),
    li("CT Scan – Abdomen/Pelvis with contrast","CPT",     "74177",  1, "each",  5800.0,  4640.0,  580.0),
    li("MRI – Abdomen without/with contrast",   "CPT",     "74183",  1, "each",  7200.0,  5760.0,  720.0),
    li("Anesthesia – General",                  "CPT",     "00840",  1, "each",  6500.0,  5200.0,  650.0),
    li("CBC (×5)",                              "CPT",     "85025",  5, "each",   750.0,   600.0,   75.0),
    li("Comprehensive Metabolic Panel (×4)",    "CPT",     "80053",  4, "each",   960.0,   768.0,   96.0),
    li("Blood Culture (×2)",                    "CPT",     "87040",  2, "each",   480.0,   384.0,   48.0),
    li("IV Administration (×7 days)",           "CPT",     "96365",  7, "each",  3360.0,  2688.0,  336.0),
    li("Pharmacy – IV Antibiotics (post-op)",   "Revenue", "0250",   1, "each",  2400.0,  1920.0,  240.0),
    li("Pharmacy – Pain Management",            "Revenue", "0250",   1, "each",  1200.0,   960.0,  120.0),
    li("Pharmacy – Anticoagulation",            "Revenue", "0250",   1, "each",   840.0,   672.0,   84.0),
    li("Physical Therapy (×3 sessions)",        "CPT",     "97110",  3, "each",   900.0,   720.0,   90.0),
    li("Medical/Surgical Supplies",             "Revenue", "0270",   1, "each",  3200.0,  2560.0,  320.0),
    li("Chest X-Ray (×3)",                      "CPT",     "71046",  3, "each",   720.0,   576.0,   72.0),
    li("Wound Care Management (×3)",            "CPT",     "97597",  3, "each",   900.0,   720.0,   90.0),
    li("Nutrition Support Consultation",        "CPT",     "97802",  1, "each",   320.0,   256.0,   32.0),
]
totals18 = make_totals(items18)
# Secondary insurance covers remaining patient balance after primary
# Remaining after primary (ins+adj removed): totals18["outstanding_balance"]
# Secondary pays most of it, leaving $500 deductible
secondary_payment = round(totals18["outstanding_balance"] - 500.0, 2)
# Rebuild with secondary in payment_detail but patient_balance stays at full outstanding
BILLS.append({
    "_schema_version": "2.0",
    "_note": NOTE,
    "facility": FACILITY,
    "statement_date": "2026-06-15",
    "due_date": "2026-07-15",
    "patient": {
        "patient_name": "Thomas Nguyen",
        "patient_account_number": "CS-2026-08450",
        "service_date": "2026-05-05"
    },
    "guarantor": {
        "guarantor_name": "Thomas Nguyen",
        "guarantor_account_number": "GU-2026-08450"
    },
    "insurance": {
        "primary": "Cigna – PPO (Commercial, employer-sponsored)",
        "secondary": "Kaiser Permanente – HMO (spouse employer-sponsored)"
    },
    "summary_of_services": {
        "line_items": items18,
        "totals": totals18
    },
    "payment_detail": {
        "insurance_payments": [
            {"payer_name": "Cigna PPO (primary)", "payment_amount": totals18["total_insurance_payments"], "payment_date": "2026-06-01", "check_or_ref_number": "CIG-2026-08450-01"},
            {"payer_name": "Kaiser Permanente HMO (secondary COB)", "payment_amount": secondary_payment, "payment_date": "2026-06-10", "check_or_ref_number": "KP-2026-08450-02"}
        ],
        "adjustments": [
            {"description": "Cigna PPO Contractual Adjustment", "amount": totals18["total_adjustments"]}
        ]
    },
    "total_amount_due": 500.0,
    "patient_services": PATIENT_SERVICES,
    "_eval_metadata": {
        "case_id": "DV2-018",
        "household_size": 4,
        "annual_income_usd": 105000,
        "fpl_percentage": 318.0,
        "expected_eligibility_tier": "Charity Care (318% FPL, HH=4)",
        "scenario_tags": ["secondary_insurance", "COB", "inpatient", "surgery", "complex"]
    }
})

# ─── BILL 19: Medicare Part B Outpatient ─────────────────────────────────────
# HH=1, income $16,800 → 105% FPL → Charity Care
# Endoscopy outpatient — patient owes 20% coinsurance
items19 = [
    li("Colonoscopy – Diagnostic",              "CPT",     "45378",  1, "each",  8200.0,  6560.0,     0.0),
    li("Polypectomy – Single Polyp",            "CPT",     "45385",  1, "each",  3200.0,  2560.0,     0.0),
    li("Pathology – Polyp",                     "CPT",     "88305",  1, "each",   640.0,   512.0,     0.0),
    li("IV Sedation – Moderate",                "CPT",     "99152",  1, "each",  1800.0,  1440.0,     0.0),
    li("Pharmacy – Propofol Sedation",          "Revenue", "0250",   1, "each",   480.0,   384.0,     0.0),
    li("Pharmacy – Bowel Prep (GoLYTELY)",      "Revenue", "0250",   1, "each",   280.0,   224.0,     0.0),
    li("Medical/Surgical Supplies",             "Revenue", "0270",   1, "each",   600.0,   480.0,     0.0),
    li("Endoscopy Suite Facility Fee",          "Revenue", "0490",   1, "each",  6800.0,  5440.0,     0.0),
]
# Medicare Part B: pays 80% of approved after deductible
# Patient owes 20% coinsurance
for item in items19:
    coinsurance = round(item["billed_amount"] * 0.20, 2)
    item["insurance_payments"] = round(item["billed_amount"] * 0.80, 2)
    item["patient_balance"] = coinsurance
totals19 = make_totals(items19)
BILLS.append({
    "_schema_version": "2.0",
    "_note": NOTE,
    "facility": FACILITY,
    "statement_date": "2026-06-01",
    "due_date": "2026-07-01",
    "patient": {
        "patient_name": "Evelyn Torres",
        "patient_account_number": "CS-2026-06714",
        "service_date": "2026-05-12"
    },
    "guarantor": {
        "guarantor_name": "Evelyn Torres",
        "guarantor_account_number": "GU-2026-06714"
    },
    "insurance": {
        "primary": "Medicare Part B (Traditional)",
        "secondary": "None on file"
    },
    "summary_of_services": {
        "line_items": items19,
        "totals": totals19
    },
    "payment_detail": {
        "insurance_payments": [
            {"payer_name": "Medicare Part B", "payment_amount": totals19["total_insurance_payments"], "payment_date": "2026-05-28", "check_or_ref_number": "MCR-2026-B-18411"}
        ],
        "adjustments": []
    },
    "total_amount_due": totals19["outstanding_balance"],
    "patient_services": PATIENT_SERVICES,
    "_eval_metadata": {
        "case_id": "DV2-019",
        "household_size": 1,
        "annual_income_usd": 16800,
        "fpl_percentage": 105.2,
        "expected_eligibility_tier": "Charity Care (105% FPL, HH=1)",
        "scenario_tags": ["medicare_part_b", "outpatient", "endoscopy", "coinsurance"]
    }
})

# ─── BILL 20: Medicaid Outpatient ────────────────────────────────────────────
# HH=1, income $14,400 → 90% FPL → Charity Care (but Medi-Cal should cover)
items20 = [
    li("Outpatient Physical Therapy – Initial Eval", "CPT", "97001", 1, "each", 800.0, 752.0, 0.0),
    li("Therapeutic Exercises (×8 sessions)",        "CPT", "97110", 8, "each", 4800.0, 4512.0, 0.0),
    li("Manual Therapy (×4 sessions)",               "CPT", "97140", 4, "each", 2400.0, 2256.0, 0.0),
    li("Ultrasound Therapy (×4 sessions)",           "CPT", "97035", 4, "each", 1200.0, 1128.0, 0.0),
    li("Neuromuscular Re-education (×2 sessions)",   "CPT", "97112", 2, "each",  960.0,  902.0, 0.0),
    li("Medical/Surgical Supplies",                  "Revenue","0270",1,"each",  320.0,  301.0, 0.0),
    li("X-Ray – Knee (3 views)",                     "CPT", "73562", 1, "each",  640.0,  602.0, 0.0),
    li("Medi-Cal Co-pay – Physical Therapy",         "Revenue","0320",10,"visit",  50.0,   0.0, 0.0),
]
# Patient owes $50 co-pay (Medi-Cal share of cost applied)
for item in items20:
    if item["service_name"].startswith("Medi-Cal"):
        item["insurance_payments"] = 0.0
        item["patient_balance"] = 50.0
totals20 = make_totals(items20)
BILLS.append({
    "_schema_version": "2.0",
    "_note": NOTE,
    "facility": FACILITY,
    "statement_date": "2026-06-01",
    "due_date": "2026-07-01",
    "patient": {
        "patient_name": "Luis Morales",
        "patient_account_number": "CS-2026-06902",
        "service_date": "2026-04-01"
    },
    "guarantor": {
        "guarantor_name": "Luis Morales",
        "guarantor_account_number": "GU-2026-06902"
    },
    "insurance": {
        "primary": "Medi-Cal (Managed Care – L.A. Care Health Plan)",
        "secondary": "None on file"
    },
    "summary_of_services": {
        "line_items": items20,
        "totals": totals20
    },
    "payment_detail": {
        "insurance_payments": [
            {"payer_name": "L.A. Care Health Plan (Medi-Cal)", "payment_amount": totals20["total_insurance_payments"], "payment_date": "2026-05-20", "check_or_ref_number": "LAC-2026-06902-01"}
        ],
        "adjustments": []
    },
    "total_amount_due": totals20["outstanding_balance"],
    "patient_services": PATIENT_SERVICES,
    "_eval_metadata": {
        "case_id": "DV2-020",
        "household_size": 1,
        "annual_income_usd": 14400,
        "fpl_percentage": 90.2,
        "expected_eligibility_tier": "Charity Care (90% FPL, HH=1) — Medi-Cal patient; verify billing error",
        "scenario_tags": ["medicaid", "outpatient", "physical_therapy", "copay"]
    }
})

# ─── BILL 21: Collections Notice ─────────────────────────────────────────────
# HH=2, income $55,500 → 176% FPL → Charity Care
# Bill sent to collections after 120 days — patient receives collection notice alongside original bill
items21 = [
    li("Emergency Department – Level 5",        "CPT",     "99285",  1, "each",  4200.0, 0.0, 0.0),
    li("OR Facility Fee – Laparoscopic",        "Revenue", "0360",   1, "each",  9800.0, 0.0, 0.0),
    li("Laparoscopic Appendectomy",             "CPT",     "44950",  1, "each", 12000.0, 0.0, 0.0),
    li("Anesthesia – General",                  "CPT",     "00840",  1, "each",  4500.0, 0.0, 0.0),
    li("Inpatient Room & Board – Semi-Private", "Revenue", "0110",   2, "day",  10000.0, 0.0, 0.0),
    li("CT Scan – Abdomen/Pelvis",              "CPT",     "74177",  1, "each",  5800.0, 0.0, 0.0),
    li("CBC + CMP",                             "CPT",     "85025",  2, "each",   720.0, 0.0, 0.0),
    li("IV Administration",                     "CPT",     "96365",  1, "each",   480.0, 0.0, 0.0),
    li("Pharmacy – IV Antibiotics",             "Revenue", "0250",   1, "each",   960.0, 0.0, 0.0),
    li("Pharmacy – Post-op Pain Management",    "Revenue", "0250",   1, "each",   600.0, 0.0, 0.0),
    li("Medical/Surgical Supplies",             "Revenue", "0270",   1, "each",  1200.0, 0.0, 0.0),
    li("Pathology – Appendix Specimen",         "CPT",     "88300",  1, "each",   480.0, 0.0, 0.0),
    li("Collections Fee (Agency Assessment)",   "Revenue", "0999",   1, "each",  1260.0, 0.0, 0.0),
]
totals21 = make_totals(items21)
BILLS.append({
    "_schema_version": "2.0",
    "_note": NOTE,
    "facility": FACILITY,
    "statement_date": "2026-06-01",
    "due_date": "2026-07-01",
    "patient": {
        "patient_name": "Angela Rivera",
        "patient_account_number": "CS-2026-01234",
        "service_date": "2026-01-15"
    },
    "guarantor": {
        "guarantor_name": "Angela Rivera",
        "guarantor_account_number": "GU-2026-01234"
    },
    "insurance": {
        "primary": "None on file",
        "secondary": "None on file"
    },
    "summary_of_services": {
        "line_items": items21,
        "totals": totals21
    },
    "payment_detail": {
        "insurance_payments": [],
        "adjustments": []
    },
    "total_amount_due": totals21["outstanding_balance"],
    "patient_services": PATIENT_SERVICES,
    "_collections_notice": {
        "collections_agency": "Cedars-Sinai Revenue Recovery",
        "original_balance": 51000.0,
        "collections_fee_added": 1260.0,
        "days_past_due": 137,
        "notice_date": "2026-06-01",
        "notice_text": "Your account has been referred to our internal collections process. You may still qualify for financial assistance. Please call 866-803-1777 immediately."
    },
    "_eval_metadata": {
        "case_id": "DV2-021",
        "household_size": 2,
        "annual_income_usd": 55500,
        "fpl_percentage": 176.0,
        "expected_eligibility_tier": "Charity Care (176% FPL, HH=2)",
        "scenario_tags": ["collections", "self_pay", "inpatient", "emergency_surgery", "retroactive_fap"]
    }
})

# ─── BILL 22: EOB Document (Commercial) ──────────────────────────────────────
# HH=2, income $82,000 → 254% FPL → Charity Care (could still apply)
# This bill shows a large EOB-style statement — high billed, significant contractual write-down
items22 = [
    li("Inpatient Room & Board – Private",      "Revenue", "0110",   5, "day",  35000.0, 21000.0, 10500.0),
    li("Cardiac Stress Test – Nuclear",         "CPT",     "78452",  1, "each",  8400.0,  5040.0,  2520.0),
    li("Echocardiogram",                        "CPT",     "93306",  1, "each",  4600.0,  2760.0,  1380.0),
    li("Cardiac Monitoring – Telemetry",        "Revenue", "0730",   5, "day",   3500.0,  2100.0,  1050.0),
    li("Comprehensive Metabolic Panel (×3)",    "CPT",     "80053",  3, "each",   720.0,   432.0,   216.0),
    li("Troponin (×3)",                         "CPT",     "84484",  3, "each",   720.0,   432.0,   216.0),
    li("Chest X-Ray (×2)",                      "CPT",     "71046",  2, "each",   480.0,   288.0,   144.0),
    li("IV Administration",                     "CPT",     "96365",  1, "each",   480.0,   288.0,   144.0),
    li("Pharmacy – Anticoagulation",            "Revenue", "0250",   1, "each",  1200.0,   720.0,   360.0),
    li("Medical/Surgical Supplies",             "Revenue", "0270",   1, "each",  1400.0,   840.0,   420.0),
]
totals22 = make_totals(items22)
BILLS.append({
    "_schema_version": "2.0",
    "_note": NOTE,
    "facility": FACILITY,
    "statement_date": "2026-06-01",
    "due_date": "2026-07-01",
    "patient": {
        "patient_name": "Karen Johnson",
        "patient_account_number": "CS-2026-07220",
        "service_date": "2026-05-01"
    },
    "guarantor": {
        "guarantor_name": "Karen Johnson",
        "guarantor_account_number": "GU-2026-07220"
    },
    "insurance": {
        "primary": "UnitedHealthcare – Choice Plus PPO (employer-sponsored)",
        "secondary": "None on file"
    },
    "summary_of_services": {
        "line_items": items22,
        "totals": totals22
    },
    "payment_detail": {
        "insurance_payments": [
            {"payer_name": "UnitedHealthcare Choice Plus PPO", "payment_amount": totals22["total_insurance_payments"], "payment_date": "2026-05-27", "check_or_ref_number": "UHC-2026-07220-01"}
        ],
        "adjustments": [
            {"description": "UnitedHealthcare Contractual Adjustment (allowed amount write-down)", "amount": totals22["total_adjustments"]}
        ]
    },
    "total_amount_due": totals22["outstanding_balance"],
    "patient_services": PATIENT_SERVICES,
    "_eval_metadata": {
        "case_id": "DV2-022",
        "household_size": 2,
        "annual_income_usd": 82000,
        "fpl_percentage": 254.0,
        "expected_eligibility_tier": "Charity Care (254% FPL, HH=2)",
        "scenario_tags": ["eob_style", "commercial_ppo", "inpatient", "cardiac", "high_deductible_balance"]
    }
})

# ─── BILL 23: FAP Approved – $0 Balance ──────────────────────────────────────
# HH=1, income $17,300 → 108% FPL → Charity Care approved; patient owes $0
items23 = [
    li("Emergency Department – Level 4",        "CPT",     "99284",  1, "each",  3200.0, 0.0, 3200.0),
    li("CT Scan – Chest with contrast",         "CPT",     "71250",  1, "each",  5600.0, 0.0, 5600.0),
    li("Pulmonary Function Test",               "CPT",     "94010",  1, "each",   560.0, 0.0,  560.0),
    li("Chest X-Ray",                           "CPT",     "71046",  1, "each",   240.0, 0.0,  240.0),
    li("CBC + CMP",                             "CPT",     "85025",  1, "each",   480.0, 0.0,  480.0),
    li("Pharmacy – Bronchodilators",            "Revenue", "0250",   1, "each",   480.0, 0.0,  480.0),
    li("IV Administration",                     "CPT",     "96365",  1, "each",   480.0, 0.0,  480.0),
    li("Medical/Surgical Supplies",             "Revenue", "0270",   1, "each",   480.0, 0.0,  480.0),
    li("Observation Services (12 hours)",       "Revenue", "0762",   1, "each",  7200.0, 0.0, 7200.0),
]
totals23 = make_totals(items23)
BILLS.append({
    "_schema_version": "2.0",
    "_note": NOTE,
    "facility": FACILITY,
    "statement_date": "2026-06-01",
    "due_date": "2026-07-01",
    "patient": {
        "patient_name": "Marcus Webb",
        "patient_account_number": "CS-2026-07005",
        "service_date": "2026-05-08"
    },
    "guarantor": {
        "guarantor_name": "Marcus Webb",
        "guarantor_account_number": "GU-2026-07005"
    },
    "insurance": {
        "primary": "None on file",
        "secondary": "None on file"
    },
    "summary_of_services": {
        "line_items": items23,
        "totals": totals23
    },
    "payment_detail": {
        "insurance_payments": [],
        "adjustments": [
            {
                "description": "Cedars-Sinai Financial Assistance Program (Charity Care)",
                "amount": totals23["total_adjustments"],
                "adjustment_date": "2026-05-25",
                "reference": "FAP-2026-07005-APPROVED",
            }
        ],
    },
    "total_amount_due": 0.0,
    "patient_services": PATIENT_SERVICES,
    "_eval_metadata": {
        "case_id": "DV2-023",
        "household_size": 1,
        "annual_income_usd": 17300,
        "fpl_percentage": 108.0,
        "expected_eligibility_tier": "Charity Care (108% FPL, HH=1) — FAP approved, $0 balance",
        "scenario_tags": ["fap_approved", "zero_balance", "self_pay", "observation"]
    }
})

# ─── BILL 24: Surprise/Balance Billing ───────────────────────────────────────
# HH=2, income $120,000 → 425% FPL → Discount Payment Plan (401-600%)
# Out-of-network provider used during in-network surgery → balance billing scenario
items24 = [
    li("OR Facility Fee (in-network)",          "Revenue", "0360",   1, "each", 14000.0, 11200.0,  1400.0),
    li("Total Hip Arthroplasty",                "CPT",     "27130",  1, "each", 32000.0, 25600.0,  3200.0),
    li("Anesthesia – General (in-network)",     "CPT",     "01402",  1, "each",  6000.0,  4800.0,   600.0),
    li("Inpatient Room & Board (in-network)",   "Revenue", "0110",   3, "day",  15000.0, 12000.0,  1500.0),
    li("Physical Therapy (in-network, ×3)",     "CPT",     "97110",  3, "each",   900.0,   720.0,    90.0),
    li("Implant – Hip Prosthesis",              "HCPCS",   "C1776",  1, "each", 12000.0,  9600.0,  1200.0),
    li("Medical/Surgical Supplies",             "Revenue", "0270",   1, "each",  2200.0,  1760.0,   220.0),
    li("Assistant Surgeon – Out-of-Network",    "CPT",     "27131",  1, "each",  8500.0,     0.0,     0.0),
    li("Pathology – Out-of-Network",            "CPT",     "88305",  1, "each",  1800.0,     0.0,     0.0),
    li("Radiology – Out-of-Network Read",       "CPT",     "72196",  1, "each",  1600.0,     0.0,     0.0),
]
totals24 = make_totals(items24)
BILLS.append({
    "_schema_version": "2.0",
    "_note": NOTE,
    "facility": FACILITY,
    "statement_date": "2026-06-15",
    "due_date": "2026-07-15",
    "patient": {
        "patient_name": "Diane Walters",
        "patient_account_number": "CS-2026-08311",
        "service_date": "2026-05-20"
    },
    "guarantor": {
        "guarantor_name": "Diane Walters",
        "guarantor_account_number": "GU-2026-08311"
    },
    "insurance": {
        "primary": "Aetna – PPO (employer-sponsored)",
        "secondary": "None on file"
    },
    "summary_of_services": {
        "line_items": items24,
        "totals": totals24
    },
    "payment_detail": {
        "insurance_payments": [
            {"payer_name": "Aetna PPO (in-network claims)", "payment_amount": totals24["total_insurance_payments"], "payment_date": "2026-06-10", "check_or_ref_number": "AET-2026-08311-01"}
        ],
        "adjustments": [
            {"description": "Aetna PPO Contractual Adjustment (in-network services)", "amount": totals24["total_adjustments"]}
        ]
    },
    "total_amount_due": totals24["outstanding_balance"],
    "patient_services": PATIENT_SERVICES,
    "_eval_metadata": {
        "case_id": "DV2-024",
        "household_size": 2,
        "annual_income_usd": 120000,
        "fpl_percentage": 425.0,
        "expected_eligibility_tier": "Discount Payment Plan (425% FPL, HH=2)",
        "scenario_tags": ["surprise_billing", "balance_billing", "out_of_network", "inpatient", "surgery"]
    }
})

# ─── BILL 25: Self-Pay Payment Plan ──────────────────────────────────────────
# HH=3, income $72,000 → 285% FPL → Charity Care
# Existing payment plan already in place — partial payments made
items25 = [
    li("Inpatient Room & Board – Semi-Private", "Revenue", "0110",   4, "day",  20000.0, 0.0, 0.0),
    li("OR Facility Fee – Spine",               "Revenue", "0360",   1, "each", 11000.0, 0.0, 0.0),
    li("Lumbar Spinal Fusion – L4-L5",          "CPT",     "22612",  1, "each", 22000.0, 0.0, 0.0),
    li("Implant – Spinal Instrumentation",      "HCPCS",   "C1713",  1, "each",  8000.0, 0.0, 0.0),
    li("Anesthesia – General",                  "CPT",     "00630",  1, "each",  5500.0, 0.0, 0.0),
    li("MRI – Lumbar Spine",                    "CPT",     "72148",  1, "each",  3800.0, 0.0, 0.0),
    li("X-Ray – Lumbar Spine (×2)",             "CPT",     "72100",  2, "each",   640.0, 0.0, 0.0),
    li("Physical Therapy (×5 inpatient)",       "CPT",     "97110",  5, "each",  1500.0, 0.0, 0.0),
    li("CBC + CMP",                             "CPT",     "85025",  2, "each",   600.0, 0.0, 0.0),
    li("Pharmacy – Pain Management",            "Revenue", "0250",   1, "each",  1200.0, 0.0, 0.0),
    li("Pharmacy – Antibiotics",                "Revenue", "0250",   1, "each",   800.0, 0.0, 0.0),
    li("IV Administration",                     "CPT",     "96365",  1, "each",   480.0, 0.0, 0.0),
    li("Medical/Surgical Supplies",             "Revenue", "0270",   1, "each",  2000.0, 0.0, 0.0),
    li("Less: Payments Received (payment plan)","Revenue", "0399",   1, "each", -9120.0, 0.0, 0.0),
]
totals25 = make_totals(items25)
BILLS.append({
    "_schema_version": "2.0",
    "_note": NOTE,
    "facility": FACILITY,
    "statement_date": "2026-06-01",
    "due_date": "2026-07-01",
    "patient": {
        "patient_name": "Carlos Espinoza",
        "patient_account_number": "CS-2026-04018",
        "service_date": "2026-02-10"
    },
    "guarantor": {
        "guarantor_name": "Carlos Espinoza",
        "guarantor_account_number": "GU-2026-04018"
    },
    "insurance": {
        "primary": "None on file",
        "secondary": "None on file"
    },
    "summary_of_services": {
        "line_items": items25,
        "totals": totals25
    },
    "payment_detail": {
        "insurance_payments": [],
        "adjustments": [],
        "payments_received": [
            {"description": "Monthly payment plan installment (×4 months)", "total_paid": 9120.0, "last_payment_date": "2026-05-15", "plan_ref": "PP-2026-04018"}
        ]
    },
    "total_amount_due": totals25["outstanding_balance"],
    "patient_services": PATIENT_SERVICES,
    "_eval_metadata": {
        "case_id": "DV2-025",
        "household_size": 3,
        "annual_income_usd": 72000,
        "fpl_percentage": 285.0,
        "expected_eligibility_tier": "Charity Care (285% FPL, HH=3)",
        "scenario_tags": ["self_pay", "payment_plan", "inpatient", "spine_surgery"]
    }
})

# ─── Write files ──────────────────────────────────────────────────────────────

filenames = [
    "bill_v2_complex_cardiac_inpatient_16.json",
    "bill_v2_maternity_inpatient_17.json",
    "bill_v2_secondary_insurance_cob_18.json",
    "bill_v2_medicare_partb_outpatient_19.json",
    "bill_v2_medicaid_outpatient_20.json",
    "bill_v2_collections_selfpay_21.json",
    "bill_v2_eob_commercial_22.json",
    "bill_v2_fap_approved_zero_balance_23.json",
    "bill_v2_surprise_balance_billing_24.json",
    "bill_v2_selfpay_payment_plan_25.json",
]

def strip_eval(bill):
    result = {k: v for k, v in bill.items() if k not in STRIP_KEYS and k != "_eval_metadata" and k != "_collections_notice"}
    return result

for bill, fname in zip(BILLS, filenames):
    # Evaluator version (full)
    with open(f"{OUT_EVAL}/{fname}", "w") as f:
        json.dump(bill, f, indent=2)
    # Agent version (stripped)
    with open(f"{OUT_AGENT}/{fname}", "w") as f:
        json.dump(strip_eval(bill), f, indent=2)
    total_due = bill.get("total_amount_due")
    case_id = bill.get("_eval_metadata", {}).get("case_id", "?")
    print(f"Written {case_id}: {fname} — total_due={total_due}")

print("\nDone. All 10 bills written.")
